# Generated by Django 5.2.7 on 2025-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agilepharm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.RemoveField(
            model_name='store',
            name='author_category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('pain-relief', 'Pain Relief'), ('vitamins', 'Vitamins & Supplements'), ('skin', 'Skin & Beauty'), ('devices', 'Health Devices'), ('medical', 'Medical Supplies')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
