# Generated by Django 5.2.7 on 2025-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agilepharm', '0002_alter_store_options_remove_store_author_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('pain-relief', 'Pain Relief'), ('vitamins', 'Vitamins & Supplements'), ('skin', 'Skin & Beauty'), ('devices', 'Health Devices'), ('Health', 'Health Devices'), ('Prescription', 'Prescription Refills'), ('Nature', 'Field Supplements'), ('WholeShield', 'WholeShield Supplements'), ('medical', 'Medical Supplies'), ('Surgicals', 'Surgicals')], max_length=50),
        ),
    ]
